export type SalesType = {
  docEntry: number;
  docNum: number;
  cardCode: string;
  cardName: string;
  salesPersonCode: number;
  salesPersonName: string;
  docDate: string;
  docDueDate: string;
  docCurrency: string;
  docTotal: number;
  docTotalFc: number;
  docTotalSys: number;
  paidToDate: number;
  paidSum: number;
  paidSumFc: 0;
  paidSumSc: 0;
  paidToDateFC: 0;
  paidToDateSys: 0;
  documentStatus: string;
  uTypeOrder: string | null;
  uFirma: string | null;
  uTipdostavka: number | null;
  uJonatildi: string;
  uYopildi: string;
  uRuxsat: string;
  uNarx: number | null;
  documentLines: {
    lineNum: number;
    itemCode: string;
    itemDescription: string;
    quantity: number;
    currency: string;
    unitPrice: number;
    price: number;
    priceFC: number;
    priceSC: number;
    lineTotal: number;
    rowTotalFC: number;
    rowTotalSC: number;
    warehouseCode: string;
    warehouseName: string;
    weight1: number;
    uomCode: string;
    uomName: string;
    lineStatus: string;
    uRulon: number | null;
    uList: number | null;
    uKesilgansoni: number | null;
  }[];
};
