export type SalesOrdersType = {
  docEntry: number;
  docNum: number;
  cardCode: string;
  cardName: string;
  salesPersonCode: number;
  salesPersonName: string;
  docDate: string;
  docDueDate: string;
  docCurrency: string;
  docTotal: number;
  docTotalFc: number;
  docTotalSys: number;
  documentStatus: string;
  uTypeOrder: string;
  uFirma: string;
  uTipdostavka: number;
  uJonatildi: string;
  uYopildi: string;
  uRuxsat: string;
  uNarx: null | string | number;
  documentLines: {
    lineNum: number;
    itemCode: string;
    itemDescription: string;
    quantity: number;
    currency: string;
    unitPrice: number;
    price: number;
    priceFC: number;
    priceSC: number;
    lineTotal: number;
    rowTotalFC: number;
    rowTotalSC: number;
    warehouseCode: string;
    warehouseName: string;
    weight1: number;
    uomCode: string;
    uomName: string;
    lineStatus: string;
  }[];
};
